apiVersion: v1
kind: Pod
metadata:
  name: java-backend
  labels:
    name: java-backend
spec:
  containers:
    - name: java-backend
      image: chmikata/java-backend:latest
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
