apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-bff-app
  namespace: argocd
spec:
  destination:
    namespace: java-bff
    server: https://kubernetes.default.svc
  project: test-project
  sources:
    - repoURL: https://github.com/chmikata/argo-sub2.git
      path: manifests/java-bff
      targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
