apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaba-backend-app
  namespace: argocd
spec:
  destination:
    namespace: java-backend
    server: https://kubernetes.default.svc
  project: test-project
  sources:
    - repoURL: https://github.com/chmikata/argo-sub2.git
      path: manifests/java-backend
      targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
